[package]
name = "midisynth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
midir = "0.9.1"
rustysynth = "1.2.1"
tinyaudio = "0.1.2"
